[package]
name = "othello_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.6.1"
byteorder = "1.4.3"

[profile.release]
opt-level = 3
lto = "fat"
